### ISSUE TITLE
{SUGGESTION] Add fortune to gems

### ISSUE THREAD

**Issue by Cynix32** [ADDSynth/Overpowered-Technology-Forge-1.16#2]
Vanilla gems like diamond and emerald utilize fortune, even nether quartz. It makes sense to make all gem ores to be affected by fortune for uniformity.

**Comment by ADDSynth** [comment]
No, you're right. This is not intentional. Fortune applies to ore blocks that drop an item, like Coal, Lapis, and Diamond. Overpowered for Minecraft 1.12 had the Fortune functionality by overriding a function in the code, but when it was ported to Minecraft 1.14, the function was removed. I had no idea they changed how the Fortune effect is applied to blocks in Minecraft 1.14. Fortune is now added to blocks by adding the apply_bonus loot table function to the loot tables of blocks. Thanks for informing me of this oversight on my part. I will approve your pull request when I'm ready to start working on this again.
